version: "2"

services:
  app:
    image: brainsum/qashot-react:0.1.0
    build:
      context: .
    labels:
      - 'traefik.backend=node'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:front.drupal.docker.localhost'
    ports:
     - "8080:8080"
    volumes:
      - ./:/home/node/src
