version: "2.4"

x-config:
  &config-file-mount
  "./config/config.php:/var/www/html/config.php:ro"

services:
  app:
    image: brainsum/qashot-react-app:1.2.2
    volumes:
      - *config-file-mount
      - "source_code:/var/www/html"

  server:
    image: brainsum/qashot-react-web:1.2.0
    depends_on:
      - app
    ports:
     - "${WEB_PORT:-8080}:80"
    volumes:
      - *config-file-mount
      - "source_code:/var/www/html:ro"

volumes:
  source_code: {}
