version: "2.4"

x-config:
  &config-file-mount
  "./config/config.php:/var/www/html/config.php:ro"

services:
  web:
    image: brainsum/qashot-react-web:1.1.0
    depends_on:
      - app
    ports:
     - "${WEB_PORT:-8080}:80"
    volumes:
      - *config-file-mount

  app:
    image: brainsum/qashot-react-app:1.1.0
    volumes:
    - *config-file-mount
